// This file is auto-generated by scripts/generate-types.js
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Generated from: FreeWaterTips.Utils/Responses/*.cs
// Last updated: 2025-11-04T15:02:44.058Z

export interface HealthResponse {
  status: string;
  timestamp: string;
  environment: string;
  cosmosConnected: boolean;
}
