// This file is auto-generated by scripts/generate-types.js
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Generated from: FreeWaterTips.Utils/Responses/*.cs
export interface HealthResponse {
  status: string;
  timestamp: string;
  environment: string;
  cosmosConnected: boolean;
}
